---
- name: Install nvm {{ nvm_version }}
  ansible.builtin.git:
    repo: "{{ nvm_git_repository }}"
    dest: "{{ nvm_install_path }}"
    version: "v{{ nvm_version }}"

- name: Source nvm
  become_user: "{{ user }}"
  ansible.builtin.blockinfile:
    path: "{{ nvm_shell_init_file }}"
    marker: "# NVM path management from ansible {mark}"
    block: |
      . {{ nvm_install_path }}/nvm.sh

- name: Install Node.js
  become_user: "{{ user }}"
  ansible.builtin.shell: ". ./nvm.sh && nvm install {{ node_version }}"
  args:
    chdir: "{{ nvm_install_path }}"
  register: nvm_install_result